repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
        stages: [commit]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        stages: [commit]

  # - repo: local
  #  hooks:
  #    - id: pytest
  #      name: pytest
  #      language: system
  #      entry: bash -c '.venv/bin/pytest -v -s && git add storage.db'
  #      always_run: true
  #      pass_filenames: false
  #      stages: [ commit ]
